name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    uses: ${{ github.repository }}/.github/workflows/lint.yml@${{ github.ref }}

  branch-protection:
    needs: lint
    uses: ${{ github.repository }}/.github/workflows/branch-protection.yml@${{ github.ref }}

  build:
    needs: lint
    uses: ${{ github.repository }}/.github/workflows/build.yml@${{ github.ref }}

  test:
    needs: build
    uses: ${{ github.repository }}/.github/workflows/test.yml@${{ github.ref }}

  versioning:
    needs: test
    uses: ${{ github.repository }}/.github/workflows/versioning.yml@${{ github.ref }}

  version-tagging:
    needs: versioning
    uses: ${{ github.repository }}/.github/workflows/version-tagging.yml@${{ github.ref }}
