name: CI Pipeline

# Define common values using YAML anchors
x-branches: &branches
  - main
  - develop

x-workflow-paths:
  lint: &lintPath ./.github/workflows/lint.yml
  branch-protection: &branchProtectionPath ./.github/workflows/branch-protection.yml
  build: &buildPath ./.github/workflows/build.yml
  test: &testPath ./.github/workflows/test.yml
  versioning: &versioningPath ./.github/workflows/versioning.yml
  version-tagging: &versionTaggingPath ./.github/workflows/version-tagging.yml

on:
  pull_request:
    branches: *branches
  push:
    branches: *branches

jobs:
  lint:
    uses: *lintPath

  branch-protection:
    needs: lint
    uses: *branchProtectionPath

  build:
    needs: lint
    uses: *buildPath

  test:
    needs: build
    uses: *testPath

  versioning:
    needs: test
    uses: *versioningPath

  version-tagging:
    needs: versioning
    uses: *versionTaggingPath
