name: CI Pipeline

# Define common branch values and reusable workflow paths as YAML anchors.
x-branches: &branches
  - main
  - develop

x-lint: &lintWorkflow "${{ github.repository }}/.github/workflows/lint.yml@${{ github.ref }}"
x-branch-protection: &branchProtectionWorkflow "${{ github.repository }}/.github/workflows/branch-protection.yml@${{ github.ref }}"
x-build: &buildWorkflow "${{ github.repository }}/.github/workflows/build.yml@${{ github.ref }}"
x-test: &testWorkflow "${{ github.repository }}/.github/workflows/test.yml@${{ github.ref }}"
x-versioning: &versioningWorkflow "${{ github.repository }}/.github/workflows/versioning.yml@${{ github.ref }}"
x-version-tagging: &versionTaggingWorkflow "${{ github.repository }}/.github/workflows/version-tagging.yml@${{ github.ref }}"

on:
  pull_request:
    branches: *branches
  push:
    branches: *branches

jobs:
  lint:
    uses: *lintWorkflow

  branch-protection:
    needs: lint
    uses: *branchProtectionWorkflow

  build:
    needs: lint
    uses: *buildWorkflow

  test:
    needs: build
    uses: *testWorkflow

  versioning:
    needs: test
    uses: *versioningWorkflow

  version-tagging:
    needs: versioning
    uses: *versionTaggingWorkflow
