name: Lint

permissions:
  pull-requests: read
on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Detect Project Type
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            node:
              - 'package.json'
            python:
              - 'requirements.txt'
              - 'pyproject.toml'
              - 'setup.py'

      - name: Set up Node.js
        if: steps.filter.outputs.node == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies (Node.js)
        if: steps.filter.outputs.node == 'true'
        run: npm install

      - name: Run ESLint (Node.js)
        if: steps.filter.outputs.node == 'true'
        run: npm run lint

      - name: Set up Python
        if: steps.filter.outputs.python == 'true'
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies (Python)
        if: steps.filter.outputs.python == 'true'
        run: |
          pip install flake8

      - name: Run Flake8 (Python)
        if: steps.filter.outputs.python == 'true'
        run: |
          flake8 .

      - name: Fail if Linting Fails
        if: failure()
        run: exit 1
